#get
### get all articles
GET http://localhost:1234/articles?search=estrella

###
GET http://localhost:1234/articles?topic=medicine

### get all
GET http://localhost:1234/articles

###get user
GET http://localhost:1234/users/cristaradmin

### get lastest articles
GET http://localhost:1234/

### get article by id
GET http://localhost:1234/articles/d12e1187-1187-43be-9e82-fe2d075d9f3e


### create an article
POST http://localhost:1234/articles
Content-Type: application/json

{
    "image":"https://firebasestorage.googleapis.com/v0/b/star-neutron.appspot.com/o/background-1.png?alt=media&token=992bb6c8-ab41-4710-9f1a-f2b5d0276bea",
   "title": "Qué es exactamente una estrella de neutrones?",
    "description": "En este artículo entenderas qué es realmente una estrella de neutrones , un cuerpo celeste que aunque pase desapercibido, es realmente sorprendente",
      "references": [
            "https://google.com",
            "https://crisdev.web.app",
            "https://youtube.com"

        ],
    "genre": "astronomy",
    "intro": "El universo, un vasto lienzo de misterio y asombro, alberga una diversidad de objetos celestes que desafían nuestra comprensión y nos instan a explorar los confines de la física teórica. Entre estas maravillas, las estrellas de neutrones ocupan un lugar destacado. Surgiendo de las espectaculares explosiones de supernovas, estas estructuras cósmicas son el resultado de la colisión entre fuerzas gravitacionales y la resistencia atómica más intensa imaginable. En este artículo, exploraremos en detalle qué son las estrellas de neutrones, cómo se forman y cuál es su importancia en el estudio del universo.",
    "conclusion": "Las estrellas de neutrones son uno de los tesoros más fascinantes que el universo nos ha revelado. Son remanentes de estrellas masivas que han vivido y muerto en explosiones espectaculares, y ahora nos brindan una ventana única para comprender los extremos de la física y la naturaleza del cosmos. Sus características únicas, como su gravedad extrema, rápida rotación y campos magnéticos poderosos, las convierten en objetos de estudio invaluables para los astrónomos y astrofísicos, permitiéndonos desentrañar los secretos del universo en una escala que desafía nuestra imaginación. El estudio continuo de las estrellas de neutrones promete desvelar aún más sobre la física fundamental y la historia de nuestro universo.",
    "body": {
        "title": "Definición",
        "body": "Una estrella de neutrones es el remanente compacto de una estrella masiva que ha agotado su combustible nuclear y ha colapsado bajo su propia gravedad. En su núcleo, la presión gravitatoria es tan extrema que provoca la fusión de electrones y protones, creando neutrones. Esta transformación da lugar a una estrella compuesta en su mayoría por neutrones densamente empaquetados, con un diámetro típico de aproximadamente 20 kilómetros. Estas estructuras son tan densas que una cucharada de materia de una estrella de neutrones pesaría miles de millones de toneladas en la Tierra."
        },
    "goodies": [
            {
                "goodie_title": "Gravedad Extrema",
                "goodie_content": "Las estrellas de neutrones son objetos astronómicos extremadamente densos, con una gravedad que desafía nuestra comprensión. En la superficie de una estrella de neutrones, la aceleración debida a la gravedad es aproximadamente un billón de veces más fuerte que en la Tierra"
            },
            {
                "goodie_title": "Rotación Rápida",
                "goodie_content": "Son pequeñas pero importantes caracteristicas que te ayudan a tener un conocimiento más amplio"
            },
            {
                "goodie_title": "Campos Magnéticos Poderosos",
                "goodie_content": "Las estrellas de neutrones también son conocidas por poseer campos magnéticos extremadamente intensos, miles de millones de veces más fuertes que el campo magnético de la Tierra"
            }
        ]
      
   
}

### delete an article
DELETE http://localhost:1234/articles/87c258c2-f400-41fe-afdc-bf562a423cb1


### updating an article

PUT  http://localhost:1234/articles/d12e1187-1187-43be-9e82-fe2d075d9f3e
Content-Type: application/json

{
    "image":"https://firebasestorage.googleapis.com/v0/b/star-neutron.appspot.com/o/background-1.png?alt=media&token=992bb6c8-ab41-4710-9f1a-f2b5d0276bea",
   "title": "Conoce realmente una estrella de neutrones",
    "description": "En este artículo entenderas qué es realmente una estrella de neutrones, un cuerpo celeste poco conocido pero realmente magestuoso",
      "references": [
            "https://google.com",
            "https://crisdev.web.app",
            "https://amazon.com"

        ],
    "genre": "astronomy",
    "intro": "El universo, un vasto lienzo de misterio y asombro, alberga una diversidad de objetos celestes que desafían nuestra comprensión y nos instan a explorar los confines de la física teórica. Entre estas maravillas, las estrellas de neutrones ocupan un lugar destacado. Surgiendo de las espectaculares explosiones de supernovas, estas estructuras cósmicas son el resultado de la colisión entre fuerzas gravitacionales y la resistencia atómica más intensa imaginable. En este artículo, exploraremos en detalle qué son las estrellas de neutrones, cómo se forman y cuál es su importancia en el estudio del universo.",
    "conclusion": "Las estrellas de neutrones son uno de los tesoros más fascinantes que el universo nos ha revelado. Son remanentes de estrellas masivas que han vivido y muerto en explosiones espectaculares, y ahora nos brindan una ventana única para comprender los extremos de la física y la naturaleza del cosmos. Sus características únicas, como su gravedad extrema, rápida rotación y campos magnéticos poderosos, las convierten en objetos de estudio invaluables para los astrónomos y astrofísicos, permitiéndonos desentrañar los secretos del universo en una escala que desafía nuestra imaginación. El estudio continuo de las estrellas de neutrones promete desvelar aún más sobre la física fundamental y la historia de nuestro universo.",
    "body": {
        "title": "Definición",
        "body": "Una estrella de neutrones es el remanente compacto de una estrella masiva que ha agotado su combustible nuclear y ha colapsado bajo su propia gravedad. En su núcleo, la presión gravitatoria es tan extrema que provoca la fusión de electrones y protones, creando neutrones. Esta transformación da lugar a una estrella compuesta en su mayoría por neutrones densamente empaquetados, con un diámetro típico de aproximadamente 20 kilómetros. Estas estructuras son tan densas que una cucharada de materia de una estrella de neutrones pesaría miles de millones de toneladas en la Tierra."
        },
    "goodies": [
            {
                "goodie_title": "Gravedad Intensa",
                "goodie_content": "Las estrellas de neutrones son objetos astronómicos extremadamente densos, con una gravedad mucho mayor a la de la tierra. En la superficie de una estrella de neutrones, la aceleración debida a la gravedad es aproximadamente un billón de veces más fuerte que en la Tierra"
            },
            {
                "goodie_title": "Rotación Rápida",
                "goodie_content": "Son pequeñas pero importantes caracteristicas que te ayudan a tener un conocimiento más amplio"
            },
            {
                "goodie_title": "Campos Magnéticos Muy Poderosos",
                "goodie_content": "Las estrellas de neutrones también son conocidas por poseer campos magnéticos extremadamente intensos, miles de millones de veces más fuertes que el campo magnético de la Tierra"
            }
        ]
      
   
}